Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -57,11 +57,12 @@ runs:
       id: derive-supported-framwork
       shell: bash
       run: |
+        # Fetch repositories.json from silverstripe/supported-modules
         RESP_CODE=$(curl -w %{http_code} -s -L -o __repositories.json \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ github.token }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
-          https://api.github.com/repos/silverstripe/silverstripe-framework/tags
+          https://raw.githubusercontent.com/silverstripe/supported-modules/refs/heads/main/repositories.json
         )
         if [[ $RESP_CODE != "200" ]]; then
           echo "Failed to fetch repositories.json - HTTP response code was $RESP_CODE"
@@ -77,6 +78,24 @@ runs:
         fi
         echo "SUPPORTED_FRAMEWORK_MAJOR is $SUPPORTED_FRAMEWORK_MAJOR"
         echo "supported_framework_major=$SUPPORTED_FRAMEWORK_MAJOR" >> "$GITHUB_OUTPUT"
+        # Make a GitHub API call to branches endpoint for silverstripe/silverstripe-framework
+        RESP_CODE=$(curl -w %{http_code} -s -L -o __branches.json \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: Bearer ${{ github.token }}" \
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          https://api.github.com/repos/silverstripe/silverstripe-framework/branches
+        )
+        if [[ $RESP_CODE != "200" ]]; then
+          echo "Failed to get list of tags - HTTP response code was $RESP_CODE"
+          cat __branches.json
+          rm __branches.json
+          exit 1
+        fi
+        # Get the highest supported framework minor branch
+        FRAMEWORK_HIGHEST_MINOR=$(jq -r --arg supported_framework_major "$SUPPORTED_FRAMEWORK_MAJOR" '[ .[] | select(.name | test("^" + $major + "\\.\\d+$")) | .name ] | sort_by(split(".") | .[1]) | .[-1]' __branches.json  | cut -d'.' -f2)
+        rm __branches.json
+        echo "FRAMEWORK_HIGHEST_MINOR is $FRAMEWORK_HIGHEST_MINOR"
+        echo "framework_highest_minor=$FRAMEWORK_HIGHEST_MINOR" >> "$GITHUB_OUTPUT"      
         # Make a GitHub API call to tags endpoint for silverstripe/silverstripe-framework
         RESP_CODE=$(curl -w %{http_code} -s -L -o __tags.json \
           -H "Accept: application/vnd.github+json" \
@@ -114,8 +133,8 @@ runs:
         GITHUB_REPOSITORY: ${{ github.repository }}
         DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
         BRANCH_TYPE: ${{ steps.derive-branch-type.outputs.branch_type }}
-        SUPPORTED_FRAMEWORK_MAJOR: ${{ steps.derive-supported-framwork.outputs.supported_framework_major }}}}
-        FRAMEWORK_TWO_TAG_EXISTS: ${{ steps.derive-supported-framwork.outputs.framework_two_tag_exists }}}}
+        SUPPORTED_FRAMEWORK_MAJOR: ${{ steps.derive-supported-framwork.outputs.supported_framework_major }}
+        FRAMEWORK_TWO_TAG_EXISTS: ${{ steps.derive-supported-framwork.outputs.framework_two_tag_exists }}
         FRAMEWORK_FOUR_TAG_EXISTS: ${{ steps.derive-supported-framwork.outputs.framework_four_tag_exists }}
       run: |
         # $DEFAULT_BRANCH is always assumed to be a numeric value i.e. not "main", and is assumed to be the same CMS version as $SUPPORTED_FRAMEWORK_MAJOR
@@ -152,7 +171,7 @@ runs:
             exit 1
           fi
           # Find the highest minor branch for major
-          HIGHEST_MINOR=$(jq -r --arg major "$MAJOR" '[ .[] | select(.name | test("^" + $major + "\\.\\d+$")) | .name ] | sort_by(split(".") | .[1]) | .[-1]' __branches.json | | cut -d'.' -f2)
+          HIGHEST_MINOR=$(jq -r --arg major "$MAJOR" '[ .[] | select(.name | test("^" + $major + "\\.\\d+$")) | .name ] | sort_by(split(".") | .[1]) | .[-1]' __branches.json | cut -d'.' -f2)
           rm __branches.json
           MODULE_BRANCH="$MAJOR.$HIGHEST_MINOR"
         fi
@@ -169,14 +188,16 @@ runs:
       env:
         BRANCH_TYPE: ${{ steps.derive-branch-type.outputs.branch_type }}
         SUPPORTED_FRAMEWORK_MAJOR: ${{ steps.derive-highest-supported-framwork-major.outputs.supported_framework_major }}
+        FRAMEWORK_HIGHEST_MINOR: ${{ steps.derive-supported-framwork.outputs.framework_highest_minor }}
       run: |
         if [[ "$BRANCH_TYPE" == "prev-major-curr-minor" ]]; then
-          MAJOR=$((SUPPORTED_FRAMEWORK_MAJOR - 4))
-          ADMIN_BRANCH="$MAJOR.4"
+          ADMIN_MAJOR=$((SUPPORTED_FRAMEWORK_MAJOR - 4))
+          ADMIN_BRANCH="$ADMIN_MAJOR.4"
+        elif [[ "$BRANCH_TYPE" == "curr-major-curr-minor" ]]; then
+          ADMIN_MAJOR=$((SUPPORTED_FRAMEWORK_MAJOR - 3))
+          ADMIN_BRANCH="$ADMIN_MAJOR.$FRAMEWORK_HIGHEST_MINOR"
         elif [[ "$BRANCH_TYPE" == 'curr-major-next-minor' ]]; then
           ADMIN_BRANCH=$((SUPPORTED_FRAMEWORK_MAJOR - 3))
-        elif [[ "$BRANCH_TYPE" == "curr-major-curr-minor" ]]; then
-          # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
         fi
         if ! [[ "$ADMIN_BRANCH" =~ ^[0-9]+$ ]] && ! [[ "$ADMIN_BRANCH" =~ ^[0-9]+\.[0-9]+$ ]]; then
           echo "ADMIN_BRANCH '$ADMIN_BRANCH' is non-numeric"
@@ -223,13 +244,15 @@ runs:
     - name: Install admin JS
       if: github.event.repository.name != 'silverstripe-admin'
       shell: bash
+      env:
+        ADMIN_BRANCH: ${{ steps.derive-admin-branch.outputs.admin_branch }}
       run: |
         # Install admin js in sibling directory so shared components are available
         DIR=$(pwd)
         cd ..
         git clone https://github.com/silverstripe/silverstripe-admin.git admin
-        # Assumption is that the default branch of admin is the correct one to build against
         cd admin
+        git checkout $ADMIN_BRANCH
         # yarn comes preinstalled with actions/setup-node
         yarn install
         cd $DIR
