Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,12 +1,63 @@
 name: Update JS
 description: Updates JS dependencies in Silverstripe core modules
 
+inputs:
+  branch:
+    description: 'The base branch to create the pull request against'
+    type: string
+    required: true
+    default: 'schedule'
+
 runs:
   using: composite
   steps:
 
+    - name: Validate inputs
+      id: validate-inputs
+      shell: bash
+      env:
+        INPUT_BRANCH: ${{ inputs.branch }}
+      run: |
+        if [[ "$INPUT_BRANCH" != "schedule" && \
+          "$INPUT_BRANCH" != "prev-major-curr-minor" && \
+          "$INPUT_BRANCH" != "curr-major-curr-minor" && \
+          "$INPUT_BRANCH" != "curr-major-next-minor" \
+        ]]; then
+          echo "Invalid INPUT_BRANCH: $INPUT_BRANCH"
+          echo "Allowed values are: schedule, prev-major-curr-minor, curr-major-curr-minor, curr-major-next-minor"
+          exit 1
+        fi
+
+    - name: Derive branch type
+      id: derive-branch
+      shell: bash
+      env:
+        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
+        INPUT_BRANCH: ${{ inputs.branch }}
+      run: |
+        if [[ $INPUT_BRANCH == 'schedule' ]]; then
+          DAY_OF_MONTH=$(date +%d)
+          if [[ "$DAY_OF_MONTH" == "01" ]]; then
+            BRANCH_TYPE="prev-major-curr-minor"
+          elif [[ "$DAY_OF_MONTH" == "02" ]]; then
+            BRANCH_TYPE="curr-major-curr-minor"
+          elif [[ "$DAY_OF_MONTH" == "03" ]]; then
+            BRANCH_TYPE="curr-major-next-minor"
+          else
+            echo "Invalid DAY_OF_MONTH: DAY_OF_MONTH"
+            echo "Allowed values are: 01, 02, 03"
+            exit 1
+          fi
+        else
+          BRANCH_TYPE="$INPUT_BRANCH"
+        fi
+        echo "BRANCH_TYPE is $BRANCH_TYPE"
+        echo "branch_type=$BRANCH_TYPE" >> "$GITHUB_OUTPUT"
+
     - name: Checkout code
       uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
+      with:
+        ref: my-feature-branch # Specify the branch name you want to checkout
 
     - name: Read .nvmrc
       id: read-nvm
